#app service
services:
  web:
    container_name: user_management_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: password
      DB_NAME: user_management
      DB_PORT: "3306"
    volumes:
      - ./Backupuserdata.txt:/backup/Backupuserdata.txt
    networks:
      - app-network

# Database service
  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./Backupuserdata.txt:/backup/Backupuserdata.txt
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes: 
  mysql_data:

networks: # Define a custom network for the application-so that the services can communicate with each other
  app-network: 
    driver: bridge