apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: my-app     #  Deployment manages Pods having this label

  template:  
    metadata:
      labels:
        app: my-app    # Pods created with this label
    spec:
      containers:
      - name: my-container
        image: nishantsahu123/user_management_project:1.7
        ports:  
        - containerPort: 5000
# here we are setting resource limits and requests for the container for scaling pods
# i have total minikube capacity 4 CPU and 3.8Gi memeory so i have devided it for 6 pod and also mysql container
        resources: 
          requests:
            memory: "200Mi"
            cpu: "200m"

          limits:
            memory: "300Mi"
            cpu: "300m"


#env for app to db connection
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PASSWORD

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec: 
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer