apiVersion: apps/v1
kind: Deployment    
metadata:
  name: mysql-deployment
spec:
  replicas: 1

  selector: 
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql 

    spec:
      containers: 
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_DATABASE
          value: "user_management"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_PASSWORD
          value: "password"
          
        ports:
        - containerPort: 3306

        volumeMounts:                                     #mount the schema.sql to the container
          - name: mysql-initdb-volume
            mountPath: /docker-entrypoint-initdb.d

          - name: mysql-storage                           # actual mysql data will be stored in this path from backend
            mountPath: /var/lib/mysql


      volumes:                                            #take the schema.sql from sql-mount-configmap
        - name: mysql-initdb-volume
          configMap:
            name: mysql-initdb-config

      volumes:                                            #take the data from /var/lib/mysql and store it in the persistent volume
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pvc

#Here both case is opposite first we mount schema.sql to the container using sql mount configmap for running the sql file 
# then mount the mysql data to the persistent volume using mysql-pvc claim 
#which is created in Persistent_volume_Claim.yml file and this claim is linked to the mysql-pv which is created in persistent_volume.yml file and store data
    
---

apiVersion: v1
kind: Service   
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  
  type: ClusterIP 