apiVersion: apps/v1
kind: Deployment    
metadata:
  name: mysql-deployment
spec:
  replicas: 1

  selector: 
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql 

    spec:
      containers: 
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_DATABASE
          value: "user_management"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_PASSWORD
          value: "password"
          
        ports:
        - containerPort: 3306

        volumeMounts:                                     #mount the schema.sql to the container
          - name: mysql-initdb-volume
            mountPath: /docker-entrypoint-initdb.d

      volumes:                                            #take the schema.sql from configmap
        - name: mysql-initdb-volume
          configMap:
            name: mysql-initdb-config
      
    
---

apiVersion: v1
kind: Service   
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  