#This file is used to create a ConfigMap in Kubernetes that contains the database configuration for the application.communication between the application and the mysql database will be done using this configmap 
kind: ConfigMap
metadata:
  name: app-config
data: 
  DB_HOST: "mysql-service"
  DB_USER: "app_user"
  DB_PASSWORD: "password"
  DB_NAME: "user_management"
  DB_PORT: "3306"