name: App deployment using kubernetes

on: 
  workflow_run:
    workflows: ["User management python application CI"]
    types:
      - completed

jobs:
  Deployment_kube:

      runs-on: ubuntu-latest

      steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: set up kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'

        - name: print workflow triggered msg
          run: echo "Workflow triggered successfully"

        - name: deploy sql config file
          run: kubectl apply -f sql-mount-config.yml

        - name: deploy mysql 
          run: kubectl apply -f database_mysql.yml

        - name: deploy app and db config 
          run: kubectl apply -f app-db-config.yml

        - name: deploy app file
          run: kubectl apply -f app-deploy.yml

        - name: print successfully deployment msg
          run: echo "App deployed successfully"

        
